phpist_core:
    resource: "@PhpistCoreBundle/Resources/config/routing.yml"
    prefix:   /

phpist_user:
    resource: "@PhpistUserBundle/Resources/config/routing.yml"
    prefix:   /user

phpist_event:
    resource: "@PhpistEventBundle/Resources/config/routing.yml"
    prefix:   /

